# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: dailype
# "service" is the name of this project. This will also be added to your AWS resource names.
service: helloCleanArchV2

provider:
  name: aws
  runtime: python3.12

# you can overwrite defaults here
  stage: ${opt:stage}
  region: ap-south-1
  vpc:
    securityGroupIds:
      - sg-dc65ccbf
    subnetIds:
      - subnet-0984343d0de359928
      - subnet-02516599457190624
  environment:
    CURRENT_STAGE: ${opt:stage}


custom:
  gitDescription: ${git:repository} - ${git:branch} - ${git:sha1} - ${git:isDirty}
  stage: ${opt:stage}
  dc_mail_list:
    dev: '["ankur@dailype.in"]'
    prod: '["dp_founder","lender_daily_collection_repayment","ashwin@dailype.in","ankur@dailype.in","prashanth@dailype.in",
            "sagar.dave@margtechno.com"]'
  log_state:
    dev: ${opt:log_state, 'INFO'}
    prod: ${opt:log_state, 'INFO'}
  pythonRequirements:
    zip: true
  iam:
    - los-${opt:stage}-ap-south-1-lambdaRole
  authorizerArn:
    dev: arn:aws:lambda:ap-south-1:779752077158:function:authorization-dev-authorizer
    prod: arn:aws:lambda:ap-south-1:779752077158:function:authorization-prod-authorizer

functions:
  hello:
    handler: serverlessHelloCleanArch.lambda_handlers.hello_handler.hello_lambda_handler
    name: ${self:service}-${sls:stage}-hello
    description: ${self:custom.gitDescription}
    timeout: 900
    events:
      - http:
          path: /hello
          method: post
          cors: true

plugins:
  - serverless-plugin-git-variables
package:
  patterns:
    - '!venv/**'
    - '!.idea/**'
    - '!.vscode/**'
