# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: dailype
# "service" is the name of this project. This will also be added to your AWS resource names.
service: helloCleanArchV2

provider:
  name: aws
  runtime: python3.12
functions:
  hello:
    handler: serverlessHelloCleanArch.lambda_handlers.hello_handler.hello_lambda_handler
    events:
      - httpApi:
          path: /
          method: post
