"""empty message

Revision ID: 49f05e23bd76
Revises: cba6b9ef4c35
Create Date: 2024-05-27 21:14:50.598825

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49f05e23bd76"
down_revision: Union[str, None] = "cba6b9ef4c35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "message",
        "message_type",
        existing_type=postgresql.ENUM("HELLO", "BYE", name="messagetype"),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "message",
        "message_type",
        existing_type=postgresql.ENUM("HELLO", "BYE", name="messagetype"),
        nullable=False,
    )
    # ### end Alembic commands ###
